### ISSUE TITLE
Secured components & multi tenancy support in nextus?

### ISSUE THREAD

**Issue by munichdeveloper** [luochuanyuewu/nextus#3]
Hi and thank you, nextus looks really cool.

I have a requirement - i need to create an application with multi tenancy support and was checking out directus (and now nextus).
As far as i can see, directus is supporting multi tenancy (in a certain way..), but nextus not really?

As far as i understand, the response you get from the login in nextus is not being used for anything, the calls to directus api are solely performed with an api token. Is that correct?

If so, there is also no support for multi tenancy, without extending nextus, right?

Appreciate your response and again, thank you so much for your work and nextus.

**Comment by luochuanyuewu** [comment]
Currently login from frontend page are not done yet. 

Also, I don't really understand what kind of multi tenant you are looking for. Though you can use nextus as a multipurpose site(blog,documentation,project showcase.) 

I'm currently using nuxtus as my personal blog, My other products(game dev related)landing page and hosting documentation of my products. On directus side, I can also tweak different permissions to allow my clients access different files.

**Comment by luochuanyuewu** [comment]
By the way, nuxtus is just a directus starter template paired with a nextjs frontend. 

People should use it as starting point instead relying it to be a full featured ready to use product.

**Comment by luochuanyuewu** [comment]
“the calls to directus api are solely performed with an api token".

It's correct, almost all data fetching calls executed on the nextjs server side (so browser can't see it)
