### ISSUE TITLE
"url" parameter is valid but upstream response is invalid

### ISSUE THREAD

**Issue by musabatas** [luochuanyuewu/nextus#6]
Images not loading on next frontend, direct access working btw.
 
_.../_next/image?url=***&w=640&q=75_
 
`"url" parameter is valid but upstream response is invalid`

`⨯ upstream image response failed for .../assets/2a7c872d-eb61-4e12-a099... 403`

**Comment by luochuanyuewu** [comment]
Thanks for reporting this, Can you tell me which route this error appears, or it's happening everywhere?

**Comment by musabatas** [comment]
Blocked everywhere.

Check the following link for example:

`https://next.betaprep.io/_next/image?url=https%3A%2F%2Fbackend.betaprep.io%2Fassets%2F2a7c872d-eb61-4e12-a099-96988b1b81bd&w=640&q=75`

**Comment by luochuanyuewu** [comment]
https://[backend.betaprep.io/assets/2a7c872d-eb61-4e12-a099-96988b1b81bd&w=640&q=75](https://backend.betaprep.io/assets/2a7c872d-eb61-4e12-a099-96988b1b81bd&w=640&q=75)

Please make sure your image from directus is public accessible. It looks like a permission problem on the directus side. 

For me, I put all my image into a directus folder called "public", and everyone can read from here.

**Comment by musabatas** [comment]
Yes, worked. 

I thought it is enough to set permissions for api users.

Thanks.
